### PR TITLE
Last Version

### PR DESCRIPTION
**Pull request by tolgaouz**

### CODE REVIEW

**Comment by tolgaouz** [comment]
Made the changes and committed 👍

**Comment by davidgatti** [comment]
Screen Shot 2020-05-27 at 9 50 30 PM (2)

- I requested the spinner to be on the side, but it is no.
- now some how we are asking for the postal code, this should not happen

Please don't add issues when you are solving the issues. Pay attention to what have you done. Look at what you have done, and make sure I don't have to point to obvious mistakes.

**Comment by tolgaouz** [comment]
Sorry David, fixed it now. About the zip-code it's not something I've changed we were always asking for the zip code

**Comment by tolgaouz** [comment]
At least that was the case in my end when I'm testing stripe

**Comment by davidgatti** [comment]
Regarding the Zip code, stragne, because when I test, I always hit the 2 button untill the form stops accepting it, and in the case of a zip it seams you can add characters for a long time, and that is why I noticed that something is off, because the form did not stop me. 

But anyway, remove the zip code if you can so Stripe dose not ask for it.

**Comment by tolgaouz** [comment]
Yep I'll look that up but maybe that happened when we switch to live version?

**Comment by tolgaouz** [comment]
nevermind figured it out 👍

**Pull request merged**
